'use client';

import { useEffect, useState } from 'react';

type ConvertedPage = {
  name: string;
  route: string;
  files: string[];
};

export default function ConvertedPagesView() {
  const [pages, setPages] = useState<ConvertedPage[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/admin/converted-pages')
      .then((r) => r.json())
      .then((data) => {
        setPages(data.pages ?? []);
        setLoading(false);
      })
      .catch((e) => {
        setError(e.message);
        setLoading(false);
      });
  }, []);

  return (
    <div style={{ padding: 24, fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', minHeight: '100vh', color: '#ddd' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
        <h1 style={{ margin: 0, fontSize: 22 }}>Converted Pages</h1>
        <a
          href="/admin/convert-page"
          style={{ padding: '8px 16px', background: '#7C3AED', color: '#fff', borderRadius: 6, textDecoration: 'none', fontSize: 13, fontWeight: 600 }}
        >
          + Convert New Page
        </a>
      </div>
      <p style={{ margin: '0 0 24px', color: '#888', fontSize: 13 }}>
        Pages generated by the AI page converter — available at their route URLs.
      </p>

      {loading && <p style={{ color: '#555' }}>Loading…</p>}
      {error && <p style={{ color: '#f87171' }}>Error: {error}</p>}

      {!loading && !error && pages.length === 0 && (
        <div style={{ padding: 48, textAlign: 'center', border: '1px dashed #333', borderRadius: 8, color: '#555' }}>
          <p style={{ fontSize: 15, marginBottom: 12 }}>No converted pages yet.</p>
          <a href="/admin/convert-page" style={{ color: '#93c5fd', fontSize: 13 }}>Convert your first page →</a>
        </div>
      )}

      {!loading && pages.length > 0 && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 16 }}>
          {pages.map((page) => (
            <div
              key={page.name}
              style={{ background: '#0f172a', border: '1px solid #1e293b', borderRadius: 8, padding: 20 }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
                <span style={{ fontFamily: 'monospace', fontSize: 15, fontWeight: 700, color: '#e2e8f0' }}>
                  /{page.name}
                </span>
                <div style={{ display: 'flex', gap: 8 }}>
                  <a
                    href={`http://localhost:3000${page.route}`}
                    target="_blank"
                    rel="noreferrer"
                    style={{ fontSize: 11, padding: '4px 10px', background: '#1e293b', color: '#93c5fd', borderRadius: 4, textDecoration: 'none', fontWeight: 500 }}
                  >
                    View ↗
                  </a>
                  <a
                    href="/admin/convert-page"
                    style={{ fontSize: 11, padding: '4px 10px', background: '#1e293b', color: '#6b7280', borderRadius: 4, textDecoration: 'none', fontWeight: 500 }}
                  >
                    Re-convert
                  </a>
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                {page.files.map((f) => (
                  <span key={f} style={{ fontSize: 11, color: '#475569', fontFamily: 'monospace' }}>
                    {f}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
