'use client';

import '../../admin.css';
import { useEffect, useState } from 'react';
import { adminStyles, Button, StatusMessage } from '../_shared';

type ConvertedPage = {
  name: string;
  route: string;
  files: string[];
};

type ResultTone = 'success' | 'error' | 'conflict';
type Result = { type: ResultTone; message: string; adminUrl?: string };

export default function ConvertedPagesView() {
  const [pages, setPages] = useState<ConvertedPage[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [uploading, setUploading] = useState<Record<string, boolean>>({});
  const [deleting, setDeleting] = useState<Record<string, boolean>>({});
  const [moreOpen, setMoreOpen] = useState<Record<string, boolean>>({});
  const [results, setResults] = useState<Record<string, Result>>({});

  useEffect(() => {
    fetch('/api/admin/converted-pages')
      .then((r) => r.json())
      .then((data) => {
        setPages(data.pages ?? []);
        setLoading(false);
      })
      .catch((e) => {
        console.error('[ConvertedPages] failed to load:', e);
        setError(e instanceof Error ? e.message : 'Failed to load converted pages.');
        setLoading(false);
      });
  }, []);

  async function uploadToCMS(pageName: string) {
    setUploading((prev) => ({ ...prev, [pageName]: true }));
    setResults((prev) => {
      const next = { ...prev };
      delete next[pageName];
      return next;
    });

    try {
      const res = await fetch('/api/admin/upload-converted-page', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ pageName }),
      });
      const data = (await res.json()) as {
        ok?: boolean;
        error?: string;
        pageId?: string;
        adminUrl?: string | null;
      };

      if (res.ok && data.ok) {
        setResults((prev) => ({
          ...prev,
          [pageName]: {
            type: 'success',
            message: 'Uploaded to CMS as draft.',
            adminUrl: data.adminUrl ?? undefined,
          },
        }));
        return;
      }

      if (res.status === 409) {
        setResults((prev) => ({
          ...prev,
          [pageName]: {
            type: 'conflict',
            message: data.error || 'Already exists in CMS.',
            adminUrl: data.adminUrl ?? undefined,
          },
        }));
        return;
      }

      setResults((prev) => ({
        ...prev,
        [pageName]: { type: 'error', message: data.error || 'Upload failed.' },
      }));
    } catch (err) {
      console.error('[ConvertedPages] upload failed:', err);
      setResults((prev) => ({
        ...prev,
        [pageName]: {
          type: 'error',
          message: err instanceof Error ? err.message : 'Upload failed.',
        },
      }));
    } finally {
      setUploading((prev) => ({ ...prev, [pageName]: false }));
    }
  }

  async function deletePage(pageName: string) {
    if (!window.confirm(`Delete /${pageName} from disk? This cannot be undone.`)) return;
    setDeleting((prev) => ({ ...prev, [pageName]: true }));
    setResults((prev) => {
      const next = { ...prev };
      delete next[pageName];
      return next;
    });

    try {
      const res = await fetch('/api/admin/converted-pages', {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ pageName }),
      });
      const data = (await res.json()) as { ok?: boolean; error?: string };
      if (res.ok && data.ok) {
        setPages((prev) => prev.filter((p) => p.name !== pageName));
      } else {
        setResults((prev) => ({
          ...prev,
          [pageName]: { type: 'error', message: data.error || 'Delete failed.' },
        }));
      }
    } catch (err) {
      console.error('[ConvertedPages] delete failed:', err);
      setResults((prev) => ({
        ...prev,
        [pageName]: {
          type: 'error',
          message: err instanceof Error ? err.message : 'Delete failed.',
        },
      }));
    } finally {
      setDeleting((prev) => ({ ...prev, [pageName]: false }));
    }
  }

  return (
    <div data-admin-view="converted-pages" style={adminStyles.container}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 'var(--admin-space-1)' }}>
        <h1 style={adminStyles.heading1}>Converted Pages</h1>
        <Button
          variant="primary"
          onClick={() => {
            window.location.href = '/admin/convert-page';
          }}
        >
          + Convert New Page
        </Button>
      </div>
      <p style={{ margin: '0 0 var(--admin-space-6)', color: 'var(--admin-text-tertiary)', fontSize: 'var(--admin-text-md)' }}>
        Pages generated by the AI page converter — available at their route URLs.
      </p>

      {loading && <p style={{ color: 'var(--admin-text-tertiary)' }}>Loading…</p>}
      {error && <StatusMessage tone="error">{error}</StatusMessage>}

      {!loading && !error && pages.length === 0 && (
        <div
          style={{
            padding: 'var(--admin-space-6)',
            textAlign: 'center',
            border: '1px dashed var(--admin-border)',
            borderRadius: 'var(--admin-radius-lg)',
            color: 'var(--admin-text-tertiary)',
          }}
        >
          <p style={{ fontSize: 'var(--admin-text-lg)', marginBottom: 'var(--admin-space-3)' }}>
            No converted pages yet.
          </p>
          <a href="/admin/convert-page" style={{ color: 'var(--admin-accent-text)', fontSize: 'var(--admin-text-md)' }}>
            Convert your first page →
          </a>
        </div>
      )}

      {!loading && pages.length > 0 && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 320px), 1fr))', gap: 'var(--admin-space-4)' }}>
          {pages.map((page) => {
            const canEdit = page.files.some((f) => f.endsWith('/content.ts'));
            const isMoreOpen = !!moreOpen[page.name];
            const result = results[page.name];
            return (
              <div key={page.name} style={adminStyles.card}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 'var(--admin-space-3)' }}>
                  <span style={{ fontFamily: 'var(--admin-font-mono)', fontSize: 'var(--admin-text-lg)', fontWeight: 700, color: 'var(--admin-text-primary)' }}>
                    /{page.name}
                  </span>
                  <div style={{ display: 'flex', gap: 'var(--admin-space-2)' }}>
                    <Button
                      size="sm"
                      variant="primary"
                      loading={uploading[page.name]}
                      onClick={() => uploadToCMS(page.name)}
                    >
                      {uploading[page.name] ? 'Uploading…' : 'Upload to CMS'}
                    </Button>
                    {canEdit ? (
                      <a
                        href={`/admin/edit-converted-page/${page.name}`}
                        style={{
                          fontSize: 'var(--admin-text-sm)',
                          padding: '4px 10px',
                          background: 'var(--admin-accent-bg)',
                          color: 'var(--admin-accent-text)',
                          borderRadius: 'var(--admin-radius-sm)',
                          textDecoration: 'none',
                          fontWeight: 600,
                          border: '1px solid var(--admin-accent)',
                        }}
                      >
                        Edit ✦
                      </a>
                    ) : (
                      <span
                        style={{
                          fontSize: 'var(--admin-text-sm)',
                          padding: '4px 10px',
                          background: 'var(--admin-bg-hover)',
                          color: 'var(--admin-text-muted)',
                          borderRadius: 'var(--admin-radius-sm)',
                          fontWeight: 600,
                          fontStyle: 'italic',
                        }}
                        title="Visual editor is available for converted pages with a content.ts file."
                      >
                        No Editor
                      </span>
                    )}
                    <Button
                      size="sm"
                      variant="secondary"
                      aria-label="More actions"
                      aria-expanded={isMoreOpen}
                      onClick={() => setMoreOpen((prev) => ({ ...prev, [page.name]: !prev[page.name] }))}
                      style={{ padding: '2px 8px', fontSize: 14, lineHeight: 1, fontWeight: 700 }}
                    >
                      ⋯
                    </Button>
                  </div>
                </div>

                {isMoreOpen && (
                  <div
                    style={{
                      display: 'flex',
                      gap: 'var(--admin-space-2)',
                      marginBottom: 'var(--admin-space-3)',
                      paddingBottom: 'var(--admin-space-3)',
                      borderBottom: '1px solid var(--admin-border-subtle)',
                    }}
                  >
                    <a
                      href={page.route}
                      target="_blank"
                      rel="noreferrer"
                      style={{
                        fontSize: 'var(--admin-text-sm)',
                        padding: '4px 10px',
                        background: 'var(--admin-bg-hover)',
                        color: 'var(--admin-accent-text)',
                        borderRadius: 'var(--admin-radius-sm)',
                        textDecoration: 'none',
                        fontWeight: 500,
                      }}
                    >
                      View ↗
                    </a>
                    <a
                      href="/admin/convert-page"
                      style={{
                        fontSize: 'var(--admin-text-sm)',
                        padding: '4px 10px',
                        background: 'var(--admin-bg-hover)',
                        color: 'var(--admin-text-tertiary)',
                        borderRadius: 'var(--admin-radius-sm)',
                        textDecoration: 'none',
                        fontWeight: 500,
                      }}
                    >
                      Re-convert
                    </a>
                    <Button
                      size="sm"
                      variant="danger"
                      loading={deleting[page.name]}
                      onClick={() => deletePage(page.name)}
                    >
                      {deleting[page.name] ? 'Deleting…' : 'Delete'}
                    </Button>
                  </div>
                )}

                {result ? (
                  <div style={{ marginBottom: 'var(--admin-space-3)' }}>
                    <StatusMessage tone={result.type === 'conflict' ? 'warning' : result.type}>
                      {result.message}
                      {result.adminUrl ? (
                        <>
                          {' '}
                          <a href={result.adminUrl} style={{ color: 'var(--admin-accent-text)', textDecoration: 'underline' }}>
                            Open
                          </a>
                        </>
                      ) : null}
                    </StatusMessage>
                  </div>
                ) : null}

                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--admin-space-1)' }}>
                  {page.files.map((f) => (
                    <span
                      key={f}
                      style={{
                        fontSize: 'var(--admin-text-sm)',
                        color: 'var(--admin-text-tertiary)',
                        fontFamily: 'var(--admin-font-mono)',
                      }}
                    >
                      {f}
                    </span>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
