/**
 * Audit tool: lists SQLite and Postgres migrations side-by-side sorted by date.
 *
 * IMPORTANT — the two systems are complementary, not duplicates:
 *
 *   Postgres (src/migrations/)
 *   - auto-generated by `npx payload migrate:create` from Payload config
 *   - must cover EVERY schema change, since Postgres does not allow runtime
 *     schema push in this setup
 *
 *   SQLite (scripts/migrations/)
 *   - hand-written ADDITIVE patches only (renames, data migrations, indexes)
 *   - base schema is created by Drizzle push (PAYLOAD_SCHEMA_PUSH=true, one time)
 *     so new tables/columns for standard Payload fields do NOT need a SQLite
 *     migration
 *
 * So "SQLite has fewer migrations" is EXPECTED. What this tool helps with is
 * spotting:
 *   - Postgres migrations that did something non-trivial (renames, data
 *     transforms) that Drizzle push can't replicate — those need a manual
 *     SQLite counterpart.
 *   - SQLite migrations for custom schema (e.g. `ensurePostgresCustomSchema`
 *     in db-migrate.ts) that Postgres handles in db-migrate code rather than
 *     a migration file.
 *
 * Usage: npm run migrations:check
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);
const projectRoot = path.resolve(dirname, '..');

const sqliteDir = path.join(projectRoot, 'scripts', 'migrations');
const postgresDir = path.join(projectRoot, 'src', 'migrations');

type Entry = {
  source: 'sqlite' | 'postgres';
  date: string; // YYYYMMDD
  name: string;
  filename: string;
};

function extractDate(filename: string): string {
  const match = filename.match(/^(\d{8})/);
  return match ? match[1] : '00000000';
}

function listMigrations(dir: string, source: 'sqlite' | 'postgres'): Entry[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter(
      (f) =>
        f.endsWith('.ts') &&
        f !== 'index.ts' &&
        f !== 'helpers.ts' &&
        f !== 'types.ts',
    )
    .map((f) => ({
      source,
      date: extractDate(f),
      name: f.replace(/\.ts$/, ''),
      filename: f,
    }));
}

function main() {
  const sqlite = listMigrations(sqliteDir, 'sqlite');
  const postgres = listMigrations(postgresDir, 'postgres');
  const all = [...sqlite, ...postgres].sort((a, b) => {
    if (a.date !== b.date) return a.date.localeCompare(b.date);
    return a.name.localeCompare(b.name);
  });

  console.log('\n=== Migration timeline ===\n');
  console.log('DATE      | SQLITE                                              | POSTGRES');
  console.log('----------|-----------------------------------------------------|---------');

  const byDate = new Map<string, { sqlite: string[]; postgres: string[] }>();
  for (const e of all) {
    if (!byDate.has(e.date)) byDate.set(e.date, { sqlite: [], postgres: [] });
    byDate.get(e.date)![e.source].push(e.name);
  }

  for (const [date, groups] of byDate) {
    const rows = Math.max(groups.sqlite.length, groups.postgres.length);
    for (let i = 0; i < rows; i++) {
      const pretty = i === 0 ? date : '        ';
      const sq = (groups.sqlite[i] ?? '').padEnd(52);
      const pg = groups.postgres[i] ?? '';
      console.log(`${pretty}  | ${sq} | ${pg}`);
    }
  }

  console.log('\n=== Summary ===');
  console.log(`  SQLite:   ${sqlite.length} migrations`);
  console.log(`  Postgres: ${postgres.length} migrations`);

  // Flag dates where only one side has a migration — this usually indicates a
  // feature was applied only to one DB. Not always a bug (Postgres auto-gen
  // bundles multiple changes into one file), but worth a human look.
  const dateOnlyInOne = [...byDate.entries()].filter(
    ([, g]) => (g.sqlite.length === 0) !== (g.postgres.length === 0),
  );
  if (dateOnlyInOne.length > 0) {
    console.log('\nℹ️  Dates where only one side has a migration:');
    for (const [date, g] of dateOnlyInOne) {
      const label = g.sqlite.length > 0 ? 'SQLite-only' : 'Postgres-only';
      const present = g.sqlite.length > 0 ? g.sqlite.join(', ') : g.postgres.join(', ');
      console.log(`  ${date}  [${label}]  ${present}`);
    }
    console.log(
      '\n  These are EXPECTED in most cases — the two systems are complementary (see header comment).',
    );
    console.log(
      '  Worth investigating manually: Postgres-only migrations whose names suggest data transforms, ' +
        'renames, or non-schema changes that Drizzle push cannot replicate.',
    );
  }
}

main();
