import type { AIMessage } from './types';

const VALID_BLOCK_TYPES = [
  'hero-block',
  'rich-text-block',
  'text-image-block',
  'cta-block',
  'faq-block',
  'stats-block',
  'testimonials-block',
  'pricing-block',
  'card-grid-block',
  'accordion-block',
  'two-col-block',
  'three-col-block',
  'logo-carousel-block',
  'video-embed-block',
  'spacer-block',
  'heading-block',
  'button-block',
  'image-block',
  'alert-block',
  'tabs-block',
  'social-icons-block',
  'counter-block',
  'progress-bar-block',
  'image-gallery-block',
  'custom-html-block',
] as const;

const REQUIRED_FIELD_GUIDE = [
  'hero-block: title (+ subtitle, primaryCtaLabel, primaryCtaHref when present)',
  'rich-text-block: content (plain string, never Lexical JSON)',
  'text-image-block: text',
  'cta-block: title, buttonLabel, buttonHref (+ subtitle optional)',
  'faq-block: items[] with {question, answer} plain strings',
  'stats-block: items[]',
  'testimonials-block: items[]',
  'pricing-block: plans[]',
  'card-grid-block: cards[]',
  'accordion-block: items[] with {heading, body} plain strings',
  'two-col-block: leftText OR rightText',
  'three-col-block: col1Text OR col2Text OR col3Text',
  'logo-carousel-block: logos[]',
  'video-embed-block: url',
  'spacer-block: height',
  'heading-block: text',
  'button-block: label, href',
  'image-block: src OR image',
  'alert-block: body',
  'tabs-block: tabs[] with {label, content}',
  'social-icons-block: links[] with {platform, url}',
  'counter-block: items[]',
  'progress-bar-block: items[]',
  'image-gallery-block: images[]',
  'custom-html-block: html',
] as const;

export function buildImportPrompt(serializedPage: string): AIMessage[] {
  const system = [
    'You are a strict Payload CMS block mapper.',
    'Return ONLY valid JSON with no markdown fences and no explanation.',
    'Output schema must be exactly:',
    '{',
    '  "blocks": PayloadSectionBlock[],',
    '  "seo": {"title"?: string, "description"?: string, "keywords"?: string, "canonicalURL"?: string, "noindex"?: boolean, "image"?: string},',
    '  "warnings": string[],',
    '  "unmappedSections": number[]',
    '}',
    '',
    'TOPOLOGY RULE (critical):',
    '- Every top-level item in "blocks" MUST be a section-block.',
    '- section-block shape: {"blockType":"section-block","columns":[{"width":"1/1"|"1/2"|"1/3"|"2/3"|"1/4"|"3/4","blocks":[PayloadBlock,...]}],"paddingTop"?:number,"paddingBottom"?:number,"backgroundColor"?:string}',
    '- Never emit a naked top-level non-section block.',
    '',
    `VALID LEAF blockType values (${VALID_BLOCK_TYPES.length}): ${VALID_BLOCK_TYPES.join(', ')}`,
    '',
    'Required field guide:',
    ...REQUIRED_FIELD_GUIDE.map((s) => `- ${s}`),
    '',
    'Fallback rule:',
    '- If a section cannot be confidently mapped, place one custom-html-block in a 1/1 column:',
    '  {"blockType":"custom-html-block","html":"<original section html>","label":"AI fallback"}',
    '- Add that section index to unmappedSections.',
    '- Preserve content. Never drop content silently.',
    '',
    'SEO rule:',
    '- Fill seo fields when inferable from headings/meta/intro content.',
    '- Keep canonicalURL empty unless clearly known.',
    '- noindex should be false unless explicitly indicated otherwise.',
    '',
    'QUALITY MAPPING RULES (critical for fidelity):',
    '- Use the exact field names listed above; do not invent aliases like description/buttonLabel for hero-block.',
    '- For text-rich fields, always return plain strings (not Lexical/document JSON objects).',
    '- Do NOT map most sections to rich-text-block by default.',
    '- rich-text-block should be used only for truly long-form prose sections.',
    '- Prefer semantic blocks whenever signals exist:',
    '  - FAQ-like section (question/answer) => faq-block or accordion-block',
    '  - Metrics/stat numbers => stats-block or counter-block',
    '  - Testimonials/quotes with names => testimonials-block',
    '  - Pricing tables/plans => pricing-block',
    '  - Grid of service cards/features => card-grid-block',
    '  - Split visual/text sections => text-image-block or two-col-block/three-col-block',
    '  - Primary action section => cta-block or button-block',
    '  - Media-heavy strips => image-block/image-gallery-block/video-embed-block',
    '  - Numbered/step-by-step process sections => accordion-block (each step = one item)',
    '  - Services list with expand/collapse per service => card-grid-block (one card per service, include tagline as text)',
    '- Preserve headings and CTA labels/URLs exactly when possible.',
    '- For service pages specifically, produce a mixed block composition (hero + cards/features + proof/testimonials + CTA), not all-rich-text.',
    '',
    'NAVIGATION AND FOOTER RULES:',
    '- Sections with role=nav or tag=nav: use custom-html-block (no native nav-block exists).',
    '- Sections with role=footer or tag=footer: use custom-html-block (no native footer-block exists).',
    '- Always add nav/footer section indices to unmappedSections.',
    '',
    'FIELD STRICTNESS:',
    '- hero-block: "title" is the H1. "subtitle" is the supporting paragraph. "primaryCtaLabel"/"primaryCtaHref" for the main CTA button.',
    '- cta-block: "title" is the heading. "buttonLabel" is the button text (NOT ctaLabel). "buttonHref" is the URL.',
    '- faq-block items: "question" and "answer" must be plain strings.',
    '- card-grid-block cards: "title" is required. "text" is the description. "ctaLabel"/"ctaHref" for the link.',
    '- stats-block items: "value" is the stat number/string (e.g. "+309%"). "label" is the description below it.',
    '',
    'Output must be parseable JSON.',
  ].join('\n');

  return [
    { role: 'system', content: system },
    {
      role: 'user',
      content: [
        'Map this parsed page payload into Payload section-block topology.',
        'Use only allowed block types and preserve all key content.',
        '',
        serializedPage,
      ].join('\n'),
    },
  ];
}
