/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  nav: {
    logo: string;
    cta: string;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  hero: {
    id: string;
    chip: string;
    description: string;
    primaryCta: string;
    secondaryCta: string;
    image?: string | null;
    imageMedia?: (number | null) | Media;
    imageAlt: string;
    badgeValue: string;
    badgeLabel: string;
    headingLines?:
      | {
          text: string;
          delay?: number | null;
          colorVar?: string | null;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value: string;
          counterTarget?: number | null;
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    marquee?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  brandAcronym: {
    id: string;
    chip: string;
    title: string;
    subtitle: string;
    items?:
      | {
          l: string;
          word: 'DASTIFY' | 'DIGITAL';
          dir: 'up' | 'down';
          color: 'purple' | 'blue';
          t1: string;
          t2: string;
          id?: string | null;
        }[]
      | null;
  };
  about: {
    id: string;
    chip: string;
    cta: string;
    image?: string | null;
    imageMedia?: (number | null) | Media;
    imageAlt: string;
    headingLines?:
      | {
          text: string;
          delay?: number | null;
          colorVar?: string | null;
          id?: string | null;
        }[]
      | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  features?: {
    cards?:
      | {
          category: string;
          title: string;
          description: string;
          image?: string | null;
          imageMedia?: (number | null) | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  caseStudies: {
    id: string;
    chip: string;
    title: string;
    cta: string;
    tabs?:
      | {
          id: string;
          label: string;
        }[]
      | null;
    main: {
      tag: string;
      title: string;
      description: string;
      stat: string;
      statLabel: string;
      image?: string | null;
      imageMedia?: (number | null) | Media;
      alt: string;
    };
    minis?:
      | {
          tag: string;
          title: string;
          stat: string;
          statLabel: string;
          image?: string | null;
          imageMedia?: (number | null) | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  services: {
    id: string;
    chip: string;
    description: string;
    titleLines?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    items?:
      | {
          number: string;
          name: string;
          description: string;
          image?: string | null;
          imageMedia?: (number | null) | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  mission: {
    chip: string;
    title: string;
    description: string;
    cta: string;
    image?: string | null;
    imageMedia?: (number | null) | Media;
    imageAlt: string;
    checks?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  insights: {
    id: string;
    chip: string;
    title: string;
    cta: string;
    items?:
      | {
          date: string;
          title: string;
          image?: string | null;
          imageMedia?: (number | null) | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    id: string;
    chip: string;
    title: string;
    intro: string;
    cta: string;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    chip: string;
    subtitle: string;
    inputPlaceholder: string;
    button: string;
    note: string;
    headingLines?:
      | {
          text: string;
          delay?: number | null;
          color?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  footer: {
    logo: string;
    tagline: string;
    copyright: string;
    socials?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    columns?:
      | {
          title: string;
          button?: string | null;
          links?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    badges?:
      | {
          label: string;
          tone?: ('blue' | 'green') | null;
          id?: string | null;
        }[]
      | null;
  };
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        logo?: T;
        cta?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  hero?:
    | T
    | {
        id?: T;
        chip?: T;
        description?: T;
        primaryCta?: T;
        secondaryCta?: T;
        image?: T;
        imageMedia?: T;
        imageAlt?: T;
        badgeValue?: T;
        badgeLabel?: T;
        headingLines?:
          | T
          | {
              text?: T;
              delay?: T;
              colorVar?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              counterTarget?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        marquee?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  brandAcronym?:
    | T
    | {
        id?: T;
        chip?: T;
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              l?: T;
              word?: T;
              dir?: T;
              color?: T;
              t1?: T;
              t2?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        id?: T;
        chip?: T;
        cta?: T;
        image?: T;
        imageMedia?: T;
        imageAlt?: T;
        headingLines?:
          | T
          | {
              text?: T;
              delay?: T;
              colorVar?: T;
              id?: T;
            };
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  features?:
    | T
    | {
        cards?:
          | T
          | {
              category?: T;
              title?: T;
              description?: T;
              image?: T;
              imageMedia?: T;
              alt?: T;
              id?: T;
            };
      };
  caseStudies?:
    | T
    | {
        id?: T;
        chip?: T;
        title?: T;
        cta?: T;
        tabs?:
          | T
          | {
              id?: T;
              label?: T;
            };
        main?:
          | T
          | {
              tag?: T;
              title?: T;
              description?: T;
              stat?: T;
              statLabel?: T;
              image?: T;
              imageMedia?: T;
              alt?: T;
            };
        minis?:
          | T
          | {
              tag?: T;
              title?: T;
              stat?: T;
              statLabel?: T;
              image?: T;
              imageMedia?: T;
              alt?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        id?: T;
        chip?: T;
        description?: T;
        titleLines?:
          | T
          | {
              text?: T;
              id?: T;
            };
        items?:
          | T
          | {
              number?: T;
              name?: T;
              description?: T;
              image?: T;
              imageMedia?: T;
              alt?: T;
              id?: T;
            };
      };
  mission?:
    | T
    | {
        chip?: T;
        title?: T;
        description?: T;
        cta?: T;
        image?: T;
        imageMedia?: T;
        imageAlt?: T;
        checks?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  insights?:
    | T
    | {
        id?: T;
        chip?: T;
        title?: T;
        cta?: T;
        items?:
          | T
          | {
              date?: T;
              title?: T;
              image?: T;
              imageMedia?: T;
              alt?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        id?: T;
        chip?: T;
        title?: T;
        intro?: T;
        cta?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        chip?: T;
        subtitle?: T;
        inputPlaceholder?: T;
        button?: T;
        note?: T;
        headingLines?:
          | T
          | {
              text?: T;
              delay?: T;
              color?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logo?: T;
        tagline?: T;
        copyright?: T;
        socials?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        columns?:
          | T
          | {
              title?: T;
              button?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        badges?:
          | T
          | {
              label?: T;
              tone?: T;
              id?: T;
            };
      };
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    global?: 'homepage' | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}